import {
  AlertTriangle,
  ArrowRight,
  ChevronLeft,
  ChevronRight,
  Command,
  CreditCard,
  FileText,
  HelpCircle,
  Laptop,
  Loader2,
  Moon,
  MoreVertical,
  Plus,
  Settings,
  SunMedium,
  Trash,
  Twitter,
  User,
  X,
  Gavel,
  FileCheck,
  DollarSign,
  TruckIcon,
  ShieldCheck,
} from "lucide-react"

export const Icons = {
  logo: Command,
  close: X,
  spinner: Loader2,
  chevronLeft: ChevronLeft,
  chevronRight: ChevronRight,
  trash: Trash,
  settings: Settings,
  billing: CreditCard,
  ellipsis: MoreVertical,
  add: Plus,
  warning: AlertTriangle,
  user: User,
  arrowRight: ArrowRight,
  help: HelpCircle,
  sun: SunMedium,
  moon: Moon,
  laptop: Laptop,
  auction: Gavel,
  verification: ShieldCheck,
  rfp: FileText,
  payment: DollarSign,
  tracking: TruckIcon,
  document: FileCheck,
  twitter: Twitter,
}

